services:
  mysql-primary:
    image: mysql:8.4
    container_name: mysql-primary-cajero
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cajero_atm
      MYSQL_USER: cajero_user
      MYSQL_PASSWORD: cajero_pass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/primary/conf.d:/etc/mysql/conf.d
      - ./mysql/primary/init:/docker-entrypoint-initdb.d
      - mysql_primary_data:/var/lib/mysql

  mysql-secondary:
    image: mysql:8.4
    container_name: mysql-secondary-cajero
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cajero_atm
      MYSQL_USER: cajero_user
      MYSQL_PASSWORD: cajero_pass
    ports:
      - "3308:3306"
    volumes:
      - ./mysql/secondary/conf.d:/etc/mysql/conf.d
      - ./mysql/secondary/init:/docker-entrypoint-initdb.d
      - mysql_secondary_data:/var/lib/mysql

  failover-monitor:
    build:
      context: ./failover-monitor
    container_name: failover-monitor-cajero
    restart: unless-stopped
    depends_on:
      - mysql-primary
      - mysql-secondary
    environment:
      PRIMARY_HOST: mysql-primary
      SECONDARY_HOST: mysql-secondary
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      APP_DB: cajero_atm
      APP_USER: cajero_user
      APP_PASSWORD: cajero_pass
      REPL_USER: replica_user
      REPL_PASSWORD: replica_pass
    volumes:
      - ../logs:/logs

volumes:
  mysql_primary_data:
  mysql_secondary_data:
